### ISSUE TITLE
Release v13.0.0-alpha.3 broken

### ISSUE THREAD

**Issue by Sigmanificient** [XAMPPRocky/tokei#1145]
- https://github.com/NixOS/nixpkgs/pull/336118

```
> results/tokei/bin/tokei --exclude nixpkgs
thread 'main' panicked at /build/tokei-13.0.0-alpha.3-vendor.tar.gz/clap_builder/src/parser/error.rs:32:9:
Mismatch between definition and access of `exclude`. Could not downcast to TypeId { t: (13369810092395217272, 7199936582794304877) }, need to downcast to TypeId { t: (12860632812102975081, 3350365521333402252) }

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)

> results/tokei/bin/tokei logs
thread 'main' panicked at /build/tokei-13.0.0-alpha.3-vendor.tar.gz/clap_builder/src/parser/error.rs:32:9:
Mismatch between definition and access of `input`. Could not downcast to TypeId { t: (13369810092395217272, 7199936582794304877) }, need to downcast to TypeId { t: (12860632812102975081, 3350365521333402252) }

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)

```

**Comment by XAMPPRocky** [comment]
Cc @qtfkwk seems to be more clap related issues.

**Comment by qtfkwk** [comment]
Confirmed behavior via:

```bash
~/github.com/qtfkwk/tokei$ git log -n 1 --pretty=format:"%h" --no-show-signature
612981e
~/github.com/qtfkwk/tokei$ cargo build
~/github.com/qtfkwk/tokei$ ./target/debug/tokei -e nixpkgs
thread 'main' panicked at src/cli.rs:327:50:
Mismatch between definition and access of `exclude`. Could not downcast to &str, need to downcast to alloc::string::String
```

**Comment by qtfkwk** [comment]
PR: https://github.com/XAMPPRocky/tokei/pull/1146

**Comment by qtfkwk** [comment]
Sorry about that @Sigmanificient! Thanks for your issue. Should be resolved following the PR and subsequent alpha release. Please confirm from your view.

**Comment by rich-purnell** [comment]
When I was using version 13.0.0-alpha.4, this error still occurred.

```
╭─u0_a288@localhost ~/Source/SJTU-IPADS/OS-Course-Lab ‹main›
╰─$ tokei --version                                                                                                                                               134 ↵
tokei 13.0.0-alpha.4 compiled with serialization support: json, cbor, yaml
╭─u0_a288@localhost ~/Source/SJTU-IPADS/OS-Course-Lab ‹main›
╰─$ tokei Lab0
thread 'main' panicked at /home/builder/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.5.15/src/parser/error.rs:32:9:
Mismatch between definition and access of `input`. Could not downcast to TypeId { t: (13369810092395217272, 7199936582794304877) }, need to downcast to TypeId { t: (5251096943531356199, 14678738461321770110) }

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    24768 abort      tokei Lab0
```

**Comment by qtfkwk** [comment]
@rich-purnell confirmed via:

```
~/github.com/qtfkwk/tokei$ git log -n 1 --pretty=format:"%h" --no-show-signature
26f1334
~/github.com/qtfkwk/tokei$ cargo build
...
~/github.com/qtfkwk/tokei$ ./target/debug/tokei src
thread 'main' panicked at src/cli.rs:334:28:
Mismatch between definition and access of `input`. Could not downcast to &str, need to downcast to alloc::string::String
```

**Comment by rich-purnell** [comment]
@qtfkwk In version 13.0.0-alpha.5, the above phenomenon has disappeared. Congratulations.
