### ISSUE TITLE
Wrong json output for C file

### ISSUE THREAD

**Issue by Luni-4** [XAMPPRocky/tokei#491]
When I run the master branch of `tokei` on the following `C` file:

```c
#include <stdio.h>

// bubble_sort_function
void bubble_sort (int a[10], int n) {
    int t;
    int j = n;
    int s = 1;
    while (s > 0) {
        s = 0;
        int i = 1;
        while (i < j) {
            if (a[i] < a[i - 1]) {
                t = a[i];
                a[i] = a[i - 1];
                a[i - 1] = t;
                s = 1;
            }
            i++;
        }
        j--;
    }
}

void main() {
    int a[] = {4, 65, 2, -31, 0, 99, 2, 83, 782, 1};
    int n = 10;
    int i = 0;

    printf("Before sorting:\n\n");
    while (i < n) {
        printf("%d ", a[i]);
        i++;
    }

    bubble_sort(a, n);

    printf("\n\nAfter sorting:\n\n");
    i = 0;
    while (i < n) {
        printf("%d ", a[i]);
        i++;
    }
}
```

The output is correct: 
```
-------------------------------------------------------------------------------
 Language            Files        Lines         Code     Comments       Blanks
-------------------------------------------------------------------------------
 C                       1           43           37            1            5
-------------------------------------------------------------------------------
 Total                   1           43           37            1            5
-------------------------------------------------------------------------------
```

But not the `json` output: 

`{"inner":{"C":{"blanks":5,"code":37,"comments":1,"lines":43,"stats":[{"blanks":5,"code":37,"comments":1,"lines":15,"name":"../../Assets/C-C++/bubble_sort.c"}],"inaccurate":false}}}`

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I've fixed this now on master, and it will be included in the next release. (Sometime this week)

**Comment by Luni-4** [comment]
Thanks a lot for your quick fix! :)

**Comment by Luni-4** [comment]
@XAMPPRocky 

Unfortunately it's still wrong

`{"inner":{"C":{"blanks":5,"code":37,"comments":1,"lines":43,"stats":[{"blanks":5,"code":37,"comments":1,"lines":28,"name":"../../Assets/C-C++/bubble_sort.c"}],"inaccurate":false}}}`

**Comment by XAMPPRocky** [comment]
@Luni-4 Whoops, I forgot to commit a part. I've pushed a proper fix, added your file into the testsuite, and added testing to make sure this can't regress.

**Comment by Luni-4** [comment]
@XAMPPRocky 

I can confirm it's now fixed! Thanks a lot, even for the addition of my file to the testsuite! :)
